# Site settings
title: Adrien Jarthon
email: me@adrienjarthon.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Adrien Jarthon, a full stack web developper who loves design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adrienjarthon.com" # the base hostname & protocol for your site
twitter_username: adrienjarthon
github_username:  jarthod

# Build settings
markdown: kramdown

collections:
  - projects